name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Change this to 'master' if your default GitHub branch is named master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build app bundle
        run: python3 public/build.py

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Hosting
        run: firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
